(() => {
  'use strict';
  const projects = [
    { number:'01', type:'WEB APPLICATION', title:'Dashboard Project', description:'차트, 메일, 파일 관리 기능을 포함한 웹 대시보드 프로젝트입니다.', tags:['React','Node.js','Socket.IO'], url:'https://dashboardkky.netlify.app/', colors:['#c7fa63','#77ad48'] },
    { number:'02', type:'MOBILE WEB', title:'Toss Clone', description:'토스 앱의 주식, 쇼핑, 혜택 기능을 구현한 모바일 버전 클론 프로젝트입니다.', tags:['React','Zustand','Express'], url:'https://tosscloneweb.netlify.app/Home', colors:['#79a9ff','#a5c4fb'] },
    { number:'03', type:'PERSONAL WEBSITE', title:'개인 포트폴리오', description:'소개와 프로젝트 탐색을 한 페이지로 연결한 반응형 웹사이트입니다.', tags:['HTML','CSS','JavaScript','Three.js'], url:'https://github.com/wellwellgood/publisher-portfolio', colors:['#ff8a62','#ffc16d'] },
  ];
  const gap=18, travel=gap*(projects.length+1);
  const $=(s)=>document.querySelector(s), canvas=$('#scene'), hero=$('.hero'), about=$('.about-panel'), ending=$('#ending'), panel=$('#project-panel'), notice=$('#notice'), progress=$('.progress i'), reduceMotion=matchMedia('(prefers-reduced-motion: reduce)');
  $('#scroll-space').style.height=`${(projects.length+2)*100}svh`;
  let reduced=reduceMotion.matches, target=0, current=0, mx=0, my=0, active=-1, renderer=null, scene, camera, orb, frame=0, last=0;
  const cards=[];
  const updateScroll=()=>{const range=document.documentElement.scrollHeight-innerHeight;target=range>0?Math.max(0,Math.min(1,scrollY/range)):0};
  function showProject(i){if(i===active)return;active=i;if(i<0){panel.classList.remove('visible');return}const p=projects[i];$('.project-number').textContent=p.number;$('.project-type').textContent=p.type;$('.project-year').textContent='PERSONAL PROJECT';$('#project-title').textContent=p.title;$('#project-description').textContent=p.description;$('#project-tags').replaceChildren(...p.tags.map(t=>{const e=document.createElement('span');e.textContent=t;return e}));const link=$('#project-link');link.href=p.url;link.replaceChildren(document.createTextNode('사이트 둘러보기 '));const arrow=document.createElement('span');arrow.setAttribute('aria-hidden','true');arrow.textContent='↗';link.append(arrow);panel.classList.add('visible')}
  function updateHud(){const d=current*travel,i=Math.round(d/gap)-1,on=i>=0&&i<projects.length&&Math.abs(d-gap*(i+1))<gap*.4;showProject(on?i:-1);const start=current<.065;hero.style.opacity=start?'1':'0';hero.style.transform=start?'translateY(0)':'translateY(18px)';hero.setAttribute('aria-hidden',String(!start));hero.inert=!start;const a=current>.855&&current<.955;about.classList.toggle('visible',a);about.inert=!a;document.body.dataset.about=String(a);const end=current>=.955;ending.classList.toggle('visible',end);ending.setAttribute('aria-hidden',String(!end));ending.inert=!end;progress.style.transform=`scaleX(${current})`;$('.scene-label span').textContent=`${on?String(i+1).padStart(2,'0'):'01'} — 03`}
  function jump(fraction){const range=document.documentElement.scrollHeight-innerHeight;window.scrollTo({top:range*fraction,behavior:reduced?'auto':'smooth'})}
  document.querySelectorAll('[data-project]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();jump((Number(a.dataset.project)+1)/(projects.length+1))}));
  $('a[href="#about"]').addEventListener('click',e=>{e.preventDefault();jump(.90)});
  addEventListener('scroll',updateScroll,{passive:true});addEventListener('resize',updateScroll,{passive:true});addEventListener('pointermove',e=>{if(e.pointerType!=='mouse'||reduced)return;mx=e.clientX/innerWidth-.5;my=e.clientY/innerHeight-.5},{passive:true});reduceMotion.addEventListener('change',e=>{reduced=e.matches});updateScroll();
  function textureFor(p){const c=document.createElement('canvas');c.width=960;c.height=600;const x=c.getContext('2d'),g=x.createLinearGradient(0,0,960,600);g.addColorStop(0,p.colors[0]);g.addColorStop(1,p.colors[1]);x.fillStyle='#141a14';x.fillRect(0,0,960,600);x.globalAlpha=.92;x.fillStyle=g;x.beginPath();x.arc(755,184,235,0,Math.PI*2);x.fill();x.globalAlpha=1;x.strokeStyle='rgba(242,245,234,.26)';x.lineWidth=2;for(let j=0;j<12;j++){x.beginPath();x.moveTo(570+j*36,0);x.lineTo(570+j*36,430);x.stroke()}x.fillStyle='rgba(16,20,17,.93)';x.fillRect(0,390,960,210);x.fillStyle='#c7fa63';x.font='500 24px monospace';x.fillText(`${p.number} / SELECTED WORK`,48,445);x.fillStyle='#f2f2eb';x.font='700 58px sans-serif';x.fillText(p.title,48,520,860);x.fillStyle='#b7beb0';x.font='400 23px monospace';x.fillText(p.tags.join('  ·  '),50,565,850);const t=new THREE.CanvasTexture(c);t.encoding=THREE.sRGBEncoding;return t}
  function init(){if(!window.THREE){notice.textContent='3D 라이브러리를 불러오지 못했습니다. 인터넷 연결을 확인해 주세요.';notice.hidden=false;canvas.hidden=true;return}try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'})}catch(_){notice.textContent='이 브라우저에서는 3D 화면을 표시할 수 없습니다. 프로젝트 정보는 계속 이용할 수 있습니다.';notice.hidden=false;canvas.hidden=true;return}
    renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.6));renderer.outputEncoding=THREE.sRGBEncoding;scene=new THREE.Scene();scene.background=new THREE.Color('#101411');scene.fog=new THREE.Fog('#101411',18,92);camera=new THREE.PerspectiveCamera(53,1,.1,180);
    projects.forEach((p,i)=>{const side=i%2===0?1:-1,g=new THREE.PlaneGeometry(8.3,5.18),card=new THREE.Mesh(g,new THREE.MeshBasicMaterial({map:textureFor(p),side:THREE.DoubleSide}));card.position.set(side*3.15,i%2===0?.45:-.25,-gap*(i+1)-12);card.rotation.y=-side*.32;card.add(new THREE.LineSegments(new THREE.EdgesGeometry(g),new THREE.LineBasicMaterial({color:0xc7fa63,transparent:true,opacity:.75})));scene.add(card);cards.push(card)});
    orb=new THREE.Group();const core=new THREE.Mesh(new THREE.IcosahedronGeometry(1.8,1),new THREE.MeshBasicMaterial({color:0xc7fa63,wireframe:true,transparent:true,opacity:.58})),ring=new THREE.Mesh(new THREE.TorusGeometry(2.7,.012,4,120),new THREE.MeshBasicMaterial({color:0xeaf7d5,transparent:true,opacity:.45}));ring.rotation.x=1.05;const ring2=ring.clone();ring2.rotation.set(.2,.8,.7);ring2.scale.setScalar(1.18);orb.add(core,ring,ring2);scene.add(orb);
    const count=innerWidth<700?600:1200,pos=new Float32Array(count*3);for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,r=6+Math.random()*22;pos[i*3]=Math.cos(a)*r;pos[i*3+1]=Math.sin(a)*r*.72;pos[i*3+2]=-Math.random()*(travel+30)}const sg=new THREE.BufferGeometry();sg.setAttribute('position',new THREE.BufferAttribute(pos,3));scene.add(new THREE.Points(sg,new THREE.PointsMaterial({color:0xd4e7c0,size:.085,transparent:true,opacity:.8,sizeAttenuation:true})));
    function resize(){if(!renderer)return;renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.6));renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.fov=innerWidth<700?63:53;camera.updateProjectionMatrix()}addEventListener('resize',resize,{passive:true});resize();canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();renderer=null;canvas.hidden=true;notice.textContent='3D 연결이 끊겼습니다. 새로고침하면 다시 시도할 수 있습니다.';notice.hidden=false})
  }
  function animate(time){if(document.hidden)return;const dt=Math.min((time-last)/1000||1/60,.05);last=time;const ease=reduced?1:1-Math.pow(1-.065,dt*60);current+=(target-current)*ease;if(reduced)current=target;updateHud();if(renderer){camera.position.z=-current*travel;const pe=1-Math.pow(1-.045,dt*60);camera.position.x+=((reduced?0:mx*1.25)-camera.position.x)*pe;camera.position.y+=((reduced?0:-my*.8)-camera.position.y)*pe;camera.lookAt(camera.position.x*.24,camera.position.y*.24,camera.position.z-12);orb.position.set(-camera.position.x*.3,-camera.position.y*.3,camera.position.z-3.2);if(!reduced){orb.rotation.x+=dt*.16;orb.rotation.y+=dt*.25;cards.forEach((card,i)=>{card.position.y=(i%2===0?.45:-.25)+Math.sin(time*.0006+i*1.7)*.13})}renderer.render(scene,camera)}frame=requestAnimationFrame(animate)}
  init();document.addEventListener('visibilitychange',()=>{cancelAnimationFrame(frame);if(!document.hidden){last=performance.now();updateScroll();frame=requestAnimationFrame(animate)}});frame=requestAnimationFrame(animate);
})();
